### ISSUE TITLE
introduce bugs

### ISSUE THREAD

**Issue by jasonLaster** [Replayio/hasreplay#24]

**Comment by ceceliacreates** [comment]
Merged some bugs in but not closing yet because I would like to add more and clean up the implementation.

**Comment by ceceliacreates** [comment]
https://app.replay.io/recording/has-replay-buggy-mode--2cc7ba04-5199-4bce-9755-29c8529379ee

**Comment by ceceliacreates** [comment]
Going to close out, will create a new issue if we want to add more bugs later.
